apiVersion: v1
kind: LimitRange
metadata:
  name: example-limitrange-container
  namespace: aula9
spec:
  limits:
    - type: Container
      max:
        cpu: "2"
        memory: "1Gi"
      min:
        cpu: "200m"
        memory: "100Mi"
---
apiVersion: v1
kind: Pod
metadata:
  name: example-limitrange-container
  namespace: aula9
spec:
  containers:
    - name: busybox-1
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "200m"
          memory: "100Mi"
        limits:
          cpu: "3" # Solicita mais cpu do que o máximo permitido de 2
          memory: "500Mi"
    - name: busybox-2
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "200m"
          memory: "100Mi"
        limits:
          cpu: "2"
          memory: "500Mi"
