apiVersion: v1
kind: LimitRange
metadata:
  name: example-limitrange-storage
  namespace: aula9
spec:
  limits:
  - type: PersistentVolumeClaim
    max:
      storage: 2Gi
    min:
      storage: 1Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-limitrange-storage-pvc
  namespace: aula9
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 3Gi  # Solicita mais armazenamento do que o máximo permitido de 2Gi
  storageClassName: standard
