apiVersion: v1
kind: ResourceQuota
metadata:
  name: example-quota
  namespace: aula9
spec:
  hard:
    pods: "2" 
    requests.cpu: "200m"
    requests.memory: "500Mi"
    limits.cpu: "1"
    limits.memory: "1Gi"
---
apiVersion: v1
kind: Deployment
metadata:
  name: example-quota-pod
  namespace: aula9
spec:
  containers:
    - name: busybox-1
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "200m"
          memory: "100Mi"
        limits:
          cpu: "700m"
          memory: "500Mi"
    - name: busybox-2
      image: busybox
      command: ["sleep", "3600"]
      resources:
        requests:
          cpu: "100m"
          memory: "100Mi"
        limits:
          cpu: "500m"
          memory: "500Mi"