apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx-custom.conf: |
    server {
        listen 80;

        location /healthz {
            return 200 "OK";
        }

        location /ready {
            return 200 "OK";
        }
    }
