apiVersion: v1
kind: Pod
metadata:
  name: example-pod
spec:
  containers:
  - name: example-container
    image: nginx
    ports:
    - containerPort: 80
    # volumeMounts:
    # - name: nginx-config-volume
    #   mountPath: /etc/nginx/conf.d
    # livenessProbe:
    #   httpGet:
    #     path: /healthz
    #     port: 80
    #   initialDelaySeconds: 15
    #   periodSeconds: 10
    # readinessProbe:
    #   httpGet:
    #     path: /ready
    #     port: 80
    #   initialDelaySeconds: 10
    #   periodSeconds: 5
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
  # volumes:
  # - name: nginx-config-volume
  #   configMap:
  #     name: nginx-config