services:
  api:
    build: ./api
    command: ["./wait-for-it.sh", "mysql-replica:3306", "--", "python", "app.py"]
    ports:
      - "8000:5000"
    depends_on:
      - redis
      - mysql-replica
    environment:
      - DB_HOST=mysql-replica
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - REDIS_HOST=redis
    volumes:
      - ./api/src:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql-master:
    image: mysql:latest
    command: --server-id=1 --log-bin=master-bin --binlog-format=ROW --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-master-data:/var/lib/mysql
  
  mysql-replica:
    image: mysql:latest
    command: --server-id=2 --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-replica-data:/var/lib/mysql

  frontend:
    build: ./frontend
    # volumes: # Uncomment this line to use local files
    #   - ./frontend/src:/usr/share/nginx/html
    ports:
      - "8081:80"
    depends_on:
      - api

  consumer:
    build: ./consumer
    command: ["./wait-for-it.sh", "mysql-master:3306", "--", "python", "app.py"]
    deploy:
      mode: replicated
      replicas: 3
    depends_on:
      - api
      - mysql-master
    environment:
      - DB_HOST=mysql-master
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - DB_PORT=3306
      - REDIS_HOST=redis
    volumes:
      - ./consumer/src:/app

  job-csv:
    build: ./job-csv
    command: ["./wait-for-it.sh", "mysql-replica:3306", "--", "python", "app.py"]
    depends_on:
      - mysql-replica
    volumes:
      - ./job-csv/src:/app
    environment:
      - DB_HOST=mysql-replica
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - DB_PORT=3306
    
  job-migration:
    build: ./job-migration
    command: ["./wait-for-it.sh", "mysql-master:3306", "--", "python", "app.py"]
    depends_on:
      - mysql-master
    volumes:
      - ./job-migration/src:/app
    environment:
      - DB_HOST=mysql-master
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - DB_PORT=3306
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 1m
      timeout: 10s
      retries: 3

volumes:
  mysql-master-data:
  mysql-replica-data: