apiVersion: v1
kind: Namespace
metadata:
  name: raspberry
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: storage-quota
  namespace: raspberry
spec:
  hard:
    requests.storage: 1Mi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-volume
  namespace: raspberry
  labels:
    app: vol
spec:
  capacity:
    storage: 128Mi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Retain
  storageClassName: standard
  nfs:
    path: "/mnt/nfsshare"
    server: 192.168.15.7
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-claim-raspberry
  namespace: raspberry
spec:
  storageClassName: standard
  selector:
    matchLabels:
      app: vol
  volumeMode: Filesystem
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
    limits:
      storage: 1Mi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox
  namespace: raspberry
  labels:
    app: busybox
spec:
  replicas: 1
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
      - image: busybox:latest
        name: busybox
        command: ["/bin/sh"]
        args: ["-c","echo 'At Work!' >> /usr/log.txt; while true; do date >> /usr/log.txt; sleep 10; done;"]
        securityContext:
          privileged: true
        volumeMounts:
          - name: nfs-volume
            mountPath: "/usr"
        resources:
          requests:
            memory: "64Mi"
            cpu: "1m"
          limits:
            memory: "128Mi"
            cpu: "2m"
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: nfs-claim-raspberry