apiVersion: v1
kind: Pod
metadata:
  name: read
  namespace: aula6
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
      - name: job-csv-volume
        mountPath: /data
  volumes:
  - name: job-csv-volume
    persistentVolumeClaim:
      claimName: job-csv-data