apiVersion: v1
kind: Pod
metadata:
  name: nfs-server-pod
spec:
  containers:
  - name: nfs-server
    image: nfs-server:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
    ports:
    - containerPort: 2049
      protocol: TCP
    - containerPort: 2049
      protocol: UDP
    - containerPort: 111
      protocol: TCP
    - containerPort: 111
      protocol: UDP
    - containerPort: 32767
      protocol: TCP
    - containerPort: 32767
      protocol: UDP
    - containerPort: 32768
      protocol: TCP
    - containerPort: 32768
      protocol: UDP
    - containerPort: 32769
      protocol: TCP
    - containerPort: 32769
      protocol: UDP
