apiVersion: v1
kind: Pod
metadata:
  name: nfs-server-pod-x
spec:
  containers:
  - name: nfs-server-x
    image: nfs-server:latest
    imagePullPolicy: IfNotPresent
    securityContext:
      privileged: true
