apiVersion: v1
kind: Service
metadata:
  name: mysql-master-service
  namespace: aula6
spec:
  type: NodePort
  ports:
    - port: 3306
      targetPort: 3306
      nodePort: 31000
  selector:
    app: mysql
---
apiVersion: v1
kind: Secret
metadata:
  name: mysql-master-secret
  namespace: aula6
type: Opaque
data:
  db_database: bXlkYXRhYmFzZQ==
  db_password: eW91cl9wYXNzd29yZA==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-master-config
  namespace: aula6
data:
  my.cnf: |
    [mysqld]
    log-bin=master-bin
    server-id=1
    binlog-format=ROW
    bind-address=0.0.0.0
    initizalize-insecure=1
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: mysql-master-8
  namespace: aula6
spec:
  serviceName: "mysql"
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.3
        args: ["--default-authentication-plugin=mysql_native_password", "--mysqlx=0"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-master-secret
              key: db_password
        - name: MYSQL_DATABASE
          valueFrom:
            secretKeyRef:
              name: mysql-master-secret
              key: db_database
        resources:
          requests:
            cpu: 100m
            memory: 100Mi
          limits:
            cpu: 500m
            memory: 400Mi
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-master-data
          mountPath: /var/lib/mysql
        # - name: config-volume
        #   mountPath: /etc/mysql/conf.d
      volumes:
      - name: config-volume
        configMap:
          name: mysql-master-config
  volumeClaimTemplates:
  - metadata:
      name: mysql-master-data
    spec:
      accessModes: ["ReadWriteOnce"]
      resources:
        requests:
          storage: 10Gi


# kubectl port-forward svc/mysql-service -n aula6 31000:3306