apiVersion: v1
kind: Secret
metadata:
  name: api-secret
  namespace: aula6
type: Opaque
data:
  db_user: cm9vdA==
  db_password: eW91cl9wYXNzd29yZA==
  db_database: bXlkYXRhYmFzZQ==
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: api-config
  namespace: aula6
data:
  db_host: "mysql-replica-service.aula6.svc.cluster.local"
  redis_host: "redis-service.aula6.svc.cluster.local"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-deployment
  namespace: aula6
spec:
  selector:
    matchLabels:
      application: api
  template:
    metadata:
      labels:
        application: api
    spec:
      containers:
      - name: api
        image: api:1.0.0
        ports:
        - containerPort: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "128Mi"
            cpu: "500m"
        env:
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db_user

        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db_password
            
        - name: DB_DATABASE
          valueFrom:
            secretKeyRef:
              name: api-secret
              key: db_database

        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: db_host
        
        - name: REDIS_HOST
          valueFrom:
            configMapKeyRef:
              name: api-config
              key: redis_host
---
apiVersion: v1
kind: Service
metadata:
  name: api-service
  namespace: aula6
spec:
  selector:
    application: api
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
      nodePort: 31150
  type: NodePort