apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  namespace: aula5
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-app-replica
  template:
    metadata:
      labels:
        app: my-app-replica
    spec:
      containers:
      - name: my-app-container
        image: node-hpa:1.1
        ports:
        - containerPort: 7878
        resources:
          requests:
            memory: "64Mi"
            cpu: "100m" # Milicores - 1/4 de CPU (250m = 0.25 CPU) (1 CPU = 1000m)
          limits:
            memory: "128Mi"
            cpu: "500m"
---
apiVersion: v1
kind: Service
metadata:
  name: my-app-service
  namespace: aula5
spec:
  selector:
    app: my-app-replica
  ports:
  - protocol: TCP
    port: 80
    targetPort: 7878
---
#apiVersion: autoscaling/v1
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: my-app-hpa
  namespace: aula5
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: my-app-deployment
  minReplicas: 1
  maxReplicas: 5
  #targetCPUUtilizationPercentage: 90
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 90
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: my-app-ingress
  namespace: aula5
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2 # Redireciona a requisição para a rota correta do serviço
    #nginx.ingress.kubernetes.io/rewrite-target: / # Redireciona a requisição para a raiz do serviço
spec:
  ingressClassName: nginx
  rules:
  - http:
      paths:
      - path: /my-app(/|$)(.*)
        pathType: ImplementationSpecific
        backend:
          service:
            name: my-app-service
            port:
              number: 80