apiVersion: v1
kind: Namespace
metadata:
  name: aula8
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: sa-pod
  namespace: aula8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: role-reader-pods
  namespace: aula8
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["list", "get"]
  #verbs: ["get"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: rb-sa-reader-pods
  namespace: aula8
subjects:
- kind: ServiceAccount
  name: sa-pod
  namespace: aula8
roleRef:
  kind: ClusterRole
  name: role-reader-pods
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Pod
metadata:
  name: pod-nginx
  namespace: aula8
spec:
  serviceAccountName: sa-pod
  containers:
  - name: kubectl-container
    image: nginx:latest
    resources:
      requests:
        cpu: 100m
        memory: 100Mi
      limits:
        cpu: 200m
        memory: 200Mi
  restartPolicy: OnFailure
