apiVersion: v1
kind: Namespace
metadata:
  name: aula8
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: developers
  namespace: aula8
rules:
- apiGroups: [""]
  resources: ["*"]
  verbs: ["list", "get", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: rb-developers-reader-pods
  namespace: aula8
subjects:
- kind: User
  name: john
  namespace: aula8
roleRef:
  kind: Role
  name: developers
  apiGroup: rbac.authorization.k8s.io