apiVersion: v1
kind: ConfigMap
metadata:
  namespace: aula4
  name: nginx-config
data:
  custom-nginx.conf: |
    server {
        listen 80;
        server_name example.com;

        location /kubernetes {
            root /usr/share/nginx/html;
            index index.html;
        }
    }
  url: http://example.com
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: aula4
type: Opaque
data:
  username: dmluaWNpdXMK
  password: c2VuaGEtdmF6YWRhCg==
---
apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
  namespace: aula4
spec:
  containers:
  - name: nginx-container
    image: nginx:latest
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-secret
          key: password
    - name: URL
      valueFrom:
        configMapKeyRef:
          name: nginx-config
          key: url
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
    volumeMounts:
    - name: nginx-config-volume
      mountPath: /etc/nginx/nginx-custom.conf
      subPath: nginx-custom.conf
  volumes:
  - name: nginx-config-volume
    configMap:
      name: nginx-config
