apiVersion: apps/v1
kind: Deployment
metadata:
  name: example-deployment
  namespace: aula4
spec:
  replicas: 1
  selector:
    matchLabels:
      app: example
  template:
    metadata:
      labels:
        app: example
    spec:
      containers:
      - name: example-container-1
        image: nginx:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      - name: example-container-2
        image: busybox:latest
        command:
          - "/bin/sh"
          - "-c"
          - "tail -f /dev/null"
        ports:
        - containerPort: 8888
        resources:
          limits:
            cpu: "0.5"
            memory: "512Mi"
          requests:
            cpu: "0.1"
            memory: "128Mi"
        volumeMounts:
        - name: data-volume
          mountPath: /data
      volumes:
      - name: data-volume
        emptyDir: {}
