services:
  api:
    build: ./api
    ports:
      - "8000:5000"
    depends_on:
      - redis
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - REDIS_HOST=redis
    volumes:
      - ./api/src:/app

  redis:
    image: redis:latest
    ports:
      - "6379:6379"

  mysql:
    image: mysql:latest
    command: --server-id=1 --log-bin=master-bin --binlog-format=ROW --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: mydatabase
      MYSQL_REPLICATION_USER: replication_user
      MYSQL_REPLICATION_PASSWORD: replication_password
    volumes:
      - mysql-master-data:/var/lib/mysql
  
  mysql-slave:
    image: mysql:latest
    command: --server-id=2 --default-authentication-plugin=mysql_native_password
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: your_password
      MYSQL_DATABASE: mydatabase
    volumes:
      - mysql-slave-data:/var/lib/mysql

  frontend:
    build: ./frontend
    # volumes: # Uncomment this line to use local files
    #   - ./frontend/src:/usr/share/nginx/html
    ports:
      - "8081:80"
    depends_on:
      - api

  consumer:
    build: ./consumer
    deploy:
      mode: replicated
      replicas: 1
    depends_on:
      - api
      - mysql
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - DB_PORT=3306
      - REDIS_HOST=redis
    volumes:
      - ./consumer/src:/app

  job-csv:
    build: ./job-csv
    depends_on:
      - mysql-slave
    volumes:
      - ./job-csv/src:/app
    environment:
      - DB_HOST=mysql-slave
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - DB_PORT=3306
    
  job-migration:
    build: ./job-migration
    depends_on:
      - mysql
    volumes:
      - ./job-migration/src:/app
    environment:
      - DB_HOST=mysql
      - DB_USER=root
      - DB_PASSWORD=your_password
      - DB_DATABASE=mydatabase
      - DB_PORT=3306

volumes:
  mysql-master-data:
  mysql-slave-data: